//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OficinaTramites.WSSeduca {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundoApellidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ci {
            get {
                return this.ciField;
            }
            set {
                if ((object.ReferenceEquals(this.ciField, value) != true)) {
                    this.ciField = value;
                    this.RaisePropertyChanged("ci");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.nombresField, value) != true)) {
                    this.nombresField = value;
                    this.RaisePropertyChanged("nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.primerApellidoField, value) != true)) {
                    this.primerApellidoField = value;
                    this.RaisePropertyChanged("primerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.segundoApellidoField, value) != true)) {
                    this.segundoApellidoField = value;
                    this.RaisePropertyChanged("segundoApellido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSSeduca.WSSeducaSoap")]
    public interface WSSeducaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verificarDatos", ReplyAction="*")]
        OficinaTramites.WSSeduca.verificarDatosResponse verificarDatos(OficinaTramites.WSSeduca.verificarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verificarDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<OficinaTramites.WSSeduca.verificarDatosResponse> verificarDatosAsync(OficinaTramites.WSSeduca.verificarDatosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerDatos", ReplyAction="*")]
        OficinaTramites.WSSeduca.obtenerDatosResponse obtenerDatos(OficinaTramites.WSSeduca.obtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<OficinaTramites.WSSeduca.obtenerDatosResponse> obtenerDatosAsync(OficinaTramites.WSSeduca.obtenerDatosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verificarDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verificarDatos", Namespace="http://tempuri.org/", Order=0)]
        public OficinaTramites.WSSeduca.verificarDatosRequestBody Body;
        
        public verificarDatosRequest() {
        }
        
        public verificarDatosRequest(OficinaTramites.WSSeduca.verificarDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class verificarDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string primerApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string segundoApellido;
        
        public verificarDatosRequestBody() {
        }
        
        public verificarDatosRequestBody(string ci, string nombres, string primerApellido, string segundoApellido) {
            this.ci = ci;
            this.nombres = nombres;
            this.primerApellido = primerApellido;
            this.segundoApellido = segundoApellido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verificarDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verificarDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public OficinaTramites.WSSeduca.verificarDatosResponseBody Body;
        
        public verificarDatosResponse() {
        }
        
        public verificarDatosResponse(OficinaTramites.WSSeduca.verificarDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class verificarDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool verificarDatosResult;
        
        public verificarDatosResponseBody() {
        }
        
        public verificarDatosResponseBody(bool verificarDatosResult) {
            this.verificarDatosResult = verificarDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerDatos", Namespace="http://tempuri.org/", Order=0)]
        public OficinaTramites.WSSeduca.obtenerDatosRequestBody Body;
        
        public obtenerDatosRequest() {
        }
        
        public obtenerDatosRequest(OficinaTramites.WSSeduca.obtenerDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public obtenerDatosRequestBody() {
        }
        
        public obtenerDatosRequestBody(string ci) {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public OficinaTramites.WSSeduca.obtenerDatosResponseBody Body;
        
        public obtenerDatosResponse() {
        }
        
        public obtenerDatosResponse(OficinaTramites.WSSeduca.obtenerDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OficinaTramites.WSSeduca.Persona obtenerDatosResult;
        
        public obtenerDatosResponseBody() {
        }
        
        public obtenerDatosResponseBody(OficinaTramites.WSSeduca.Persona obtenerDatosResult) {
            this.obtenerDatosResult = obtenerDatosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSSeducaSoapChannel : OficinaTramites.WSSeduca.WSSeducaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSeducaSoapClient : System.ServiceModel.ClientBase<OficinaTramites.WSSeduca.WSSeducaSoap>, OficinaTramites.WSSeduca.WSSeducaSoap {
        
        public WSSeducaSoapClient() {
        }
        
        public WSSeducaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSeducaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSeducaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSeducaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OficinaTramites.WSSeduca.verificarDatosResponse OficinaTramites.WSSeduca.WSSeducaSoap.verificarDatos(OficinaTramites.WSSeduca.verificarDatosRequest request) {
            return base.Channel.verificarDatos(request);
        }
        
        public bool verificarDatos(string ci, string nombres, string primerApellido, string segundoApellido) {
            OficinaTramites.WSSeduca.verificarDatosRequest inValue = new OficinaTramites.WSSeduca.verificarDatosRequest();
            inValue.Body = new OficinaTramites.WSSeduca.verificarDatosRequestBody();
            inValue.Body.ci = ci;
            inValue.Body.nombres = nombres;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.segundoApellido = segundoApellido;
            OficinaTramites.WSSeduca.verificarDatosResponse retVal = ((OficinaTramites.WSSeduca.WSSeducaSoap)(this)).verificarDatos(inValue);
            return retVal.Body.verificarDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OficinaTramites.WSSeduca.verificarDatosResponse> OficinaTramites.WSSeduca.WSSeducaSoap.verificarDatosAsync(OficinaTramites.WSSeduca.verificarDatosRequest request) {
            return base.Channel.verificarDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<OficinaTramites.WSSeduca.verificarDatosResponse> verificarDatosAsync(string ci, string nombres, string primerApellido, string segundoApellido) {
            OficinaTramites.WSSeduca.verificarDatosRequest inValue = new OficinaTramites.WSSeduca.verificarDatosRequest();
            inValue.Body = new OficinaTramites.WSSeduca.verificarDatosRequestBody();
            inValue.Body.ci = ci;
            inValue.Body.nombres = nombres;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.segundoApellido = segundoApellido;
            return ((OficinaTramites.WSSeduca.WSSeducaSoap)(this)).verificarDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OficinaTramites.WSSeduca.obtenerDatosResponse OficinaTramites.WSSeduca.WSSeducaSoap.obtenerDatos(OficinaTramites.WSSeduca.obtenerDatosRequest request) {
            return base.Channel.obtenerDatos(request);
        }
        
        public OficinaTramites.WSSeduca.Persona obtenerDatos(string ci) {
            OficinaTramites.WSSeduca.obtenerDatosRequest inValue = new OficinaTramites.WSSeduca.obtenerDatosRequest();
            inValue.Body = new OficinaTramites.WSSeduca.obtenerDatosRequestBody();
            inValue.Body.ci = ci;
            OficinaTramites.WSSeduca.obtenerDatosResponse retVal = ((OficinaTramites.WSSeduca.WSSeducaSoap)(this)).obtenerDatos(inValue);
            return retVal.Body.obtenerDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OficinaTramites.WSSeduca.obtenerDatosResponse> OficinaTramites.WSSeduca.WSSeducaSoap.obtenerDatosAsync(OficinaTramites.WSSeduca.obtenerDatosRequest request) {
            return base.Channel.obtenerDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<OficinaTramites.WSSeduca.obtenerDatosResponse> obtenerDatosAsync(string ci) {
            OficinaTramites.WSSeduca.obtenerDatosRequest inValue = new OficinaTramites.WSSeduca.obtenerDatosRequest();
            inValue.Body = new OficinaTramites.WSSeduca.obtenerDatosRequestBody();
            inValue.Body.ci = ci;
            return ((OficinaTramites.WSSeduca.WSSeducaSoap)(this)).obtenerDatosAsync(inValue);
        }
    }
}
